### ISSUE TITLE
Show Any Axis to Logarithmic

### ISSUE THREAD

**Issue by PacManPk** [team-moeller/better-access-charts#144]
Hello,

It is most often required to show some axis in logarithmic form. It would great addition in the this repo if such possiblity is added. How could it be added by code (any suggestions if I want to add it on my own).

Best Regards

**Comment by team-moeller** [comment]
Hi,
as I stated in issue #142, I will not update Better Access Charts for chart.js version 2.9.4. You must use this version because you cannot use the new edge browser control. So you must do the necessary changes on your own.
Here is a link to the spefic page in the doc for chart.js 2.9.4:
https://www.chartjs.org/docs/2.9.4/developers/updates.html?h=logarithmic
And here you can find a step-by-step guide to add a feature from chart.js to Better Access Charts:
https://github.com/team-moeller/better-access-charts/wiki/add-a-feature

If there are no further questions, please let me know if we can close this issue.

**Comment by PacManPk** [comment]
Thanks for reply. Just tell me that is the latest release has this functionality so that I see the implementation and modify my version of the BAC.

**Comment by team-moeller** [comment]
Hi @PacManPk ,
the lastest release of Better Access Chart does not support logarithmic axis.
Maybe in a few days ... :-)

**Comment by team-moeller** [comment]
See:  #145

**Comment by team-moeller** [comment]
Hi @PacManPk!
With release 3.22.07 a property to control, the axis type is implemented.
So you should now have the necessary information to enhance your version of BAC.
I will close this issue. If there are further questions, please reopen this issue.
