### ISSUE TITLE
cls_Better_Access_Chart.cls is imported as Module

### ISSUE THREAD

**Issue by sten-schmidt** [team-moeller/better-access-charts#45]
When importing cls_Better_Access_Chart.cls into a fresh Access-Database, a new Module ("Modul1") is created. 
Expected was the Import a new Class-Module.

**Comment by team-moeller** [comment]
Thank you for bringing this issue to my attention.
However, your pull request is only a one-time solution. This is due to my process of deploying a new version. Whenever I create a new version, I export the class module. For this I use the function "PrepareAndExportClassModule" from the module "mdl_Helpers".
The first thing I will do now is to accept your pull request. Then I will expand the mentioned function so that your additions are included in the file.

**Comment by team-moeller** [comment]
I have now changed the code in the mentioned function.
Instead of "Application.SaveAsText" I now use the export method from the VBComponent.
