### ISSUE TITLE
WebBrowserControl not available on endless forms

### ISSUE THREAD

**Issue by KDGundermann** [team-moeller/better-access-charts#89]
Ich have an endless for in my application where in the footer are two graph controls:

![image](https://user-images.githubusercontent.com/208315/150606360-282586a5-9f35-4bb5-881a-28333b531075.png)

but sadly a WebBrowser Control is not allowed in endless forms...
![image](https://user-images.githubusercontent.com/208315/150606251-a119b2dc-385c-4210-8af5-5647f8e64b7d.png)

**Comment by KDGundermann** [comment]
a Access.WebBrowserControl is only a small wrapper around a [SHDocVw.Webbrowser](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa752084(v=vs.85))  ActiveX-Control aka InternetExplorer object.

And Access allows you to place this ActiveX control on a endless form!  
Design -> Controls -> ActiveX controls -> search for "Microsoft Web Browser"

**Comment by KDGundermann** [comment]
Proposal: Allow BAC_Chart to accept a SHDocVw.Webbrowser control

**Comment by KentGorrell** [comment]
How about Downloading the charts to image files and display them in image controls?

**Comment by team-moeller** [comment]
@KentGorrell 
This idea has been in my head for a very long time. So far I haven't found a solution. It would be great if you can provide a code example. This would help a lot.

**Comment by KentGorrell** [comment]
I was hoping you may have code to do this 
but I do think this would take Better Access Charts to a new level
so let's work on this together...

Our current problem is that, until MS release their new Browser control for Access (November 2020?) we are going to face all sorts of problems, not the least of which is using the new version of Chartjs. Whereas MS did a whole lot of improvement on image controls in 2007 and they work brilliantly.

• There are many ways to skin this cat.
to start if you look at the HTML produced using the option "Show Download Link"
`function download() {
        var myChart = document.getElementById('myChart');
        var blob = myChart.msToBlob()
        window.navigator.msSaveBlob(blob, 'Beta-Access-Charts.png');

if we could call this function`in DrawChart()  rather than
`Control.Object.Navigate getHTMLFileName`
we should be able to download the file.
even if it means that we load the chart into a Browser control on a hidden form first. which may not return optimum results.

Better quality (and the ability to use the latest version of Chartjs) may be achieved by bypassing the brower control all together and instead open the chart in a proper browser (Chrome or Firefox), then Save to a Local File, using the Canvas object.
[https://github.com/eligrey/FileSaver.js](url)
[https://github.com/eligrey/canvas-toBlob.js](url)

I'm guessing (Hoping) that this will be quite easy. ONCE we know how to do it. Selenium may even be useful to do this.
[https://github.com/florentbr/SeleniumBasic](url)

Objectives: 
with local files we can identify the Chart by its file name and set the control source of multiple image controls.
We can avoid having to build a chart every time we need it if the data is unlikely to have been changed.
in a multi user environment, users can share the same image file and image files can be archived for historical charting.
we avoid the restrictions of the current browser control.
we can even display charts in rows in a continuous form and not just in the footer.

I'll do some more research and see what I can find.

**Comment by KDGundermann** [comment]
Hi Kent,
maybe we could include it as an additional option.
But we will loose the interactivity from ChartJS

> and the ability to use the latest version of Chartjs
we would like to use the latest version too, but currently we are blocked 
as the colorschemes plugin is not available for the newest version

> with local files
I don't like to have local files created, which (currently) never get cleaned up..

**Comment by team-moeller** [comment]
HI @KentGorrell ,
yesterday evening I took another attempt at this topic. What can I say: in the end I found a solution that allows me to save the generated chart as a file on disk without user intervention. I'm very happy!

OK, I still have to change the code a lot. I use too many references. Here I have to switch to late binding. Then there is the question of whether I want the chart to be created in a hidden form or whether I use a non-visible instance of Internet Explorer for this. Both ways have advantages and disadvantages.
I think I will continue to work on this topic for the next few days and then present a first release that allows the chart to be saved as a file using VBA. This is the first step for Better Access Charts in reports.

**Comment by KentGorrell** [comment]
Thomas, what format are you saving the file to? png or jpg? I can't wait to see how you've done it.

**Comment by KentGorrell** [comment]
cleaning up files is easy to manage if you only ever have one file per chart and if you keep them all in one folder. 
I'd been naming my html files using the form and control name when using multiple charts on the same or on multiple forms and this seemed to be manageable so I haven't bothered to delete all the files on exiting the application.

I'm not having any problem with references and early binding makes developement easier. but switching to late binding is always good practice when releasing to end users. I'd be inclined to leave them as early binding for now.

**Comment by team-moeller** [comment]
Hi @KentGorrell !
> Thomas, what format are you saving the file to? png or jpg?
In the current state the file is saved in png format.

**Comment by KentGorrell** [comment]
Excellent! thanks Thomas.

**Comment by team-moeller** [comment]
Original problem (show chart in webbrowser activeX control) basicly fixed with PR #92. Released with version 2.14.14
Support for image controls will come soon. :-)

**Comment by team-moeller** [comment]
Hi @KentGorrell !
With version 2.16.06 Better Access Chart can show the chart in an image control.
Enjoy

**Comment by KentGorrell** [comment]
Thank You Thomas, 

The Image Control works on the 64 bit version of Office on my laptop
but on my PC with 32 bit Office
fails on Set objIE = CreateObject("InternetExplorer.Application")
Active-X component can't create object.

I tried Early Binding which compiles OK but fails on the instantiation with the error
Class not registered

At this point I'm not sure if it's an issue with ExplorerFrame.dll as opposed to ieFrame.dll in wow64?
or whether I have a broken dll on this machine. 
Or whether this is the result of not having IE 11 installed on the PC. It seems to have disappeared with the appearance of Edge. While on the laptop I get an IE 11 Setup Wizard after running this code.

Do you have any insights on this?
Otherwise I'll test on another 32 bit office install and do some more research.

The webbrowser activeX control works rather well, and I get Karl's point on the interactive elements but for a printed report and continuous forms, the image control is a good option.

**Comment by KentGorrell** [comment]
Problem solved. I installed Internet Explorer, Settings > Apps > Optional Features > Add a feature
Had to type in Internet Explorer because it wasn't in the list.
Took a while to install, still didn't work. Required a restart.

**Comment by KentGorrell** [comment]
Interesting. I have previously developed using Internet Explorer on this machine.
Why is there no compile error? Even with early binding.
You might like to put a comment or test in the code to check if ie exists C:\Program Files\Internet Explorer\iexplore.exe

Thanks Thomas, great work.
